#!/bin/bash

LD_LIBRARY_PATH=/home/fshakib/webapps/hhms_django/apache2/lib:/home/fshakib/webapps/hhms_django/lib:/home/fshakib/lib/python2.7 /home/fshakib/webapps/hhms_django/apache2/bin/httpd.worker -f /home/fshakib/webapps/hhms_django/apache2/conf/httpd.conf -k restart
